//lo pueden borrar despues a esto, pero es porque no tenemos base de datos todavia, entonces para que se vea bonito y no este vacio, lo puse asi
// Datos de ejemplo del Sprint 2.
// Reemplazar por la respuesta del backend cuando exista el endpoint de Equipo.

export const miembros = [
  {
    id: 1,
    nombre: "Juan Smoes",
    iniciales: "JS",
    rol: "Profesor",
    tipoRol: "docente",
    cuenta: "Admin",
    area: "Electrotecnia & Automatización",
    correo: "jsmoes@eestflow.edu.ar",
    turno: "Turno Mañana / Turno Tarde",
    estado: "Activo en línea",
    disponible: true,
    destacado: false,
  },
  {
    id: 2,
    nombre: "Lucía Beltrán",
    iniciales: "LB",
    rol: "Jefa Taller",
    tipoRol: "taller",
    cuenta: "Colaborador",
    area: "Mecanizado & Control Numérico CNC",
    correo: "lbeltran@eestflow.edu.ar",
    turno: "Turno Completo (Rotativo)",
    estado: "En Taller 2",
    disponible: true,
    destacado: false,
  },
  {
    id: 3,
    nombre: "Marcos Daneri",
    iniciales: "MD",
    rol: "Preceptor",
    tipoRol: "preceptoria",
    cuenta: "Colaborador",
    area: "Preceptoría 4to y 5to Año",
    correo: "mdaneri@eestflow.edu.ar",
    turno: "Turno Mañana (07:30 - 13:00)",
    estado: "En Guardia",
    disponible: true,
    destacado: false,
  },
  {
    id: 4,
    nombre: "Valeria Gómez",
    iniciales: "VG",
    rol: "Profesora",
    tipoRol: "docente",
    cuenta: "Colaborador",
    area: "Sistemas Informáticos & Redes",
    correo: "vgomez@eestflow.edu.ar",
    turno: "Turno Tarde / Turno Vespertino",
    estado: "En Clase (Lab 3)",
    disponible: true,
    destacado: false,
  },
  {
    id: 5,
    nombre: "Roberto Benítez",
    iniciales: "RB",
    rol: "M. Enseñanza Práctica",
    tipoRol: "taller",
    cuenta: "Colaborador",
    area: "Soldadura & Herrería Técnica",
    correo: "rbenitez@eestflow.edu.ar",
    turno: "Turno Mañana (Pañol & Herrería)",
    estado: "En Pañol",
    disponible: true,
    destacado: false,
  },
  {
    id: 6,
    nombre: "Mariana Rossi",
    iniciales: "MR",
    rol: "Directora",
    tipoRol: "direccion",
    cuenta: "Admin",
    area: "Dirección General & Secretaría Técnica",
    correo: "mrossi@eestflow.edu.ar",
    turno: "Gestión Institucional Central",
    estado: "En Despacho",
    disponible: true,
    destacado: true,
  },
];

export const vistasRapidas = [
  { id: "todos", etiqueta: "Todos", cantidad: 28 },
  { id: "docentes", etiqueta: "Docentes de Aula", cantidad: 14 },
  { id: "tecnicos", etiqueta: "Maestros Técnicos", cantidad: 8 },
  { id: "preceptoria", etiqueta: "Preceptoría", cantidad: 4 },
  { id: "administradores", etiqueta: "Administradores", cantidad: 2 },
];

export const totalMiembros = 28;